# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for ai-usage — single-file standalone binary."""

a = Analysis(
    ['src/ai_usage/main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        # Textual internals that PyInstaller may miss
        'textual',
        'textual.app',
        'textual.widgets',
        'textual.screen',
        'textual.containers',
        'textual.css',
        'textual.css.query',
        'textual._text_area_theme',
        # Rich (Textual dependency)
        'rich',
        'rich.console',
        'rich.table',
        'rich.text',
        'rich.markup',
        'rich.traceback',
        # Typer / Click
        'typer',
        'typer.main',
        'click',
        # httpx + transport
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'httpcore',
        'h11',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        # Pydantic
        'pydantic',
        'pydantic.main',
        'pydantic_core',
        # Keyring (macOS backend)
        'keyring',
        'keyring.backends',
        'keyring.backends.macOS',
        # YAML
        'yaml',
        # Our app modules
        'ai_usage',
        'ai_usage.domain',
        'ai_usage.domain.models',
        'ai_usage.domain.events',
        'ai_usage.domain.exceptions',
        'ai_usage.ports',
        'ai_usage.ports.auth',
        'ai_usage.ports.usage',
        'ai_usage.ports.storage',
        'ai_usage.adapters',
        'ai_usage.adapters.claude',
        'ai_usage.adapters.claude.auth',
        'ai_usage.adapters.claude.usage',
        'ai_usage.adapters.chatgpt',
        'ai_usage.adapters.chatgpt.auth',
        'ai_usage.adapters.chatgpt.usage',
        'ai_usage.adapters.copilot',
        'ai_usage.adapters.copilot.auth',
        'ai_usage.adapters.copilot.usage',
        'ai_usage.adapters.storage',
        'ai_usage.adapters.storage.file',
        'ai_usage.adapters.cookies',
        'ai_usage.app',
        'ai_usage.app.account_manager',
        'ai_usage.app.usage_service',
        'ai_usage.ui',
        'ai_usage.ui.tui',
        'ai_usage.ui.tui.app',
        'ai_usage.ui.tui.screens',
        'ai_usage.ui.tui.screens.dashboard',
        'ai_usage.ui.tui.screens.accounts',
        'ai_usage.ui.tui.widgets',
        'ai_usage.ui.tui.widgets.usage_card',
        'ai_usage.ui.cli',
        'ai_usage.ui.cli.commands',
        # Certifi (for HTTPS)
        'certifi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['hooks/hook-certifi-runtime.py'],
    excludes=[
        'tkinter',
        'unittest',
        'test',
        'xmlrpc',
        'pydoc',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ai-usage',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
